### ISSUE TITLE
bug after 92%

### ISSUE THREAD

**Issue by krefects** [JijaProGamer/Youtube-View-Bot#17]
The system stops working after 92%, and shows the error message:
ProtocolError: Protocol error (Network.getCookies): Target closed.
    at C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:325:16)
    at CDPPage.cookies (C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Page.js:348:91)
    at Object.requestInterceptor (file:///C:/apps/boot/node_modules/youtube-selfbot-api/index.js:49:37)
    at file:///C:/apps/boot/node_modules/puppeteer-extra-plugin-fingerprinter/index.js:254:48
    at C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:111:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HTTPRequest.finalizeInterceptions (C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\HTTPRequest.js:188:9)
C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329
                error: new Errors_js_1.ProtocolError(),
                       ^

ProtocolError: Protocol error (Network.getCookies): Target closed.
    at C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:329:24
    at new Promise (<anonymous>)
    at CDPSessionImpl.send (C:\apps\boot\node_modules\puppeteer-core\lib\cjs\puppeteer\common\Connection.js:325:16)
    at Object.getCookies (C:\apps\boot\node_modules\puppeteer-page-proxy\src\lib\cdp.js:6:38)
    at CookieHandler.getCookies (C:\apps\boot\node_modules\puppeteer-page-proxy\src\lib\cookies.js:87:51)
    at requestHandler (C:\apps\boot\node_modules\puppeteer-page-proxy\src\core\proxy.js:15:40)
    at Object.HTTPRequest (C:\apps\boot\node_modules\puppeteer-page-proxy\src\core\proxy.js:73:27)
    at useProxy (C:\apps\boot\node_modules\puppeteer-page-proxy\src\core\proxy.js:92:41)
    at file:///C:/apps/boot/node_modules/puppeteer-extra-plugin-fingerprinter/index.js:265:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.0

![Sem título](https://github.com/JijaProGamer/Youtube-View-Bot/assets/17180773/0eb4b15b-fb6e-49d4-b866-fe0487ce168b)

**Comment by JijaProGamer** [comment]
Will be fixed in the next version, thanks.
